### ISSUE TITLE
examples of `YNGKP_M0` *not* optimizing 

### ISSUE THREAD

**Issue by skhilton** [jbloomlab/phydms#13]
@jbloom: Here are two examples of `YNGKP_M0` `phydms` runs which consistently do *not* optimize. That is, the likelihood optimization goes through one iteration and does not update any of the parameter values.  I have run into similar problems with the `ExpCM` but strangely those errors do not appear to happen consistently. 
[YNGKP_M0_error.zip](https://github.com/jbloomlab/phydms/files/994641/YNGKP_M0_error.zip)

**Comment by jbloom** [comment]
@skhilton: I think I made some progress on this. In very rare cases, it appears that the model param optimization does nothing even though the parameters are quite bad and Jacobian is still very large.

Previously, if nothing improved during model param optimization, the program just concluded everything had worked. I fixed that bug by making it always take at least one pass through the branch length optimization in commit [cf49cc0](https://github.com/jbloomlab/phydms/commit/cf49cc0a953bf4728e6d76423791c023a53afacd). At least on the example that you provided, after the one pass through the branch lengths then the model params optimize correctly, so this fixes the problem provided you are using `--brlen optimize` (which you are in your example).

If you are using `--brlen scale`, then there is no opportunity for branch length optimization. In this case, it will report having succeeded with a very large Jacobian. So I added a check that will raise a `RuntimeError` if the maximization completes with a large Jacobian. This does not fix the problem, but at least causes an error to be raised. This is done by commit [bf24669](https://github.com/jbloomlab/phydms/commit/bf24669c069d10579e7fc94be356884beda61faa).

I can't figure out the source of the bug. It may be some internal problem in the `scipy` optimizer. 

Alternatively, it may be that in these simulated trees there is some rare issue where some branch lengths are too large and some are too small relative to the starting tree used to do the simulations. Perhaps then the model param optimization pulls in two different directions for these different branches, hence the problem -- and hence why it is fixed by passing over the branch lengths for optimization once. In this case, the reason we wouldn't have found it before is that we haven't tried simulated trees, but just ones inferred with different programs where generally all branch lengths will be too large or small.

Anyway, pull the latest version from `GitHub` and see if it fixes the problem for all the runs you are doing. The hope is that it should since I think you're always using `--brlen optimize`.

If it fixes things, report that here and then we can tag this new version and put it on `PyPI`.

**Comment by skhilton** [comment]
@jbloom: I have not pulled and tested `bf24669` but I have been working with the changes in `cf49cc0` all morning. So far, I have not had any `phydms` runs with *no* change in log likelihood, even for the `ExpCM`. 

Seeing as some of my simulations probably are rather extreme test cases, I think this can probably go as the new version on `PyPI`.

**Comment by jbloom** [comment]
Can you still pull the latest version and run it on some more simulations, and then late me know if it works even after `bf24669`?

I just want to make sure that the new check isn't causing some unexpected problem before putting on `PyPI`. If you pull this last version and it runs through a reasonable number of simulations OK, let me know and I'll make this the new version.

**Comment by skhilton** [comment]
@jbloom: I pulled the latest version and ran some of my simulations. I didn't get an errors (using `--brlen optimize`)

**Comment by jbloom** [comment]
OK, I put the new version up as `2.0.4`
